import io
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.exceptions import (
    ExportTypeUnsupportedError,
    SessionNotFoundError,
    ValidationError,
)
from app.domain.exports import ExportStatus
from app.repositories.export_repo import ExportRepository
from app.repositories.finding_repo import FindingRepository
from app.repositories.models import Export
from app.repositories.negotiation_repo import NegotiationRepository
from app.repositories.session_repo import SessionRepository
from app.storage.client import storage_client


class ExportService:
    def __init__(self, db: AsyncSession, current_user_id: str | None = None) -> None:
        self.db = db
        self.current_user_id = current_user_id
        self.session_repo = SessionRepository(db)
        self.finding_repo = FindingRepository(db)
        self.negotiation_repo = NegotiationRepository(db)
        self.export_repo = ExportRepository(db)

    async def create_export(
        self,
        session_id: str,
        export_format: str,
        contents: dict[str, Any],
    ) -> Export:
        fmt = export_format.lower().strip()
        if fmt not in ("pdf", "docx"):
            raise ExportTypeUnsupportedError(f"Export format '{fmt}' unsupported. Use 'pdf' or 'docx'.")

        session = await self.session_repo.get_by_id(session_id, user_id=self.current_user_id)
        if not session:
            raise SessionNotFoundError("Session not found.")

        exp = await self.export_repo.create(
            session_id=session.id,
            format=fmt,
            contents=contents,
        )

        # Generate artifact file bytes
        artifact_bytes = self._render_export_file(fmt, session.title or "Contract Analysis", contents)
        storage_key = f"sessions/{session.id}/exports/{exp.id}.{fmt}"
        storage_client.put_object(storage_key, artifact_bytes)

        expires_at = datetime.now(UTC) + timedelta(seconds=settings.EXPORT_ARTIFACT_TTL_SECONDS)
        await self.export_repo.update_status(
            exp.id,
            status=ExportStatus.READY.value,
            storage_key=storage_key,
            url_expires_at=expires_at,
        )
        await self.db.commit()
        return exp

    def _render_export_file(self, fmt: str, title: str, contents: dict[str, Any]) -> bytes:
        if fmt == "docx":
            import docx

            doc = docx.Document()
            doc.add_heading(f"LexiClear Counter-Offer & Findings: {title}", level=1)
            doc.add_paragraph("Generated by LexiClear AI-Powered Legal Analysis Platform")

            findings = contents.get("findings", [])
            if findings:
                doc.add_heading("Findings & Statutory Violations", level=2)
                for f in findings:
                    doc.add_paragraph(f"- {f}")

            counters = contents.get("counter_clauses", [])
            if counters:
                doc.add_heading("Proposed Counter-Clauses", level=2)
                for c in counters:
                    doc.add_paragraph(f"Counter Provision:\n{c}")

            bio = io.BytesIO()
            doc.save(bio)
            return bio.getvalue()

        # PDF format fallback / binary
        return b"%PDF-1.4 LexiClear Report " + title.encode() + b"\n%%EOF"

    async def get_export(self, export_id: str) -> dict:
        exp = await self.export_repo.get_by_id(export_id)
        if not exp:
            raise ValidationError("Export record not found.")

        url = ""
        if exp.storage_key:
            url = storage_client.generate_signed_url(exp.storage_key, expires_in=300)

        filename = f"lexiclear-counter-offer.{exp.format}"
        return {
            "id": exp.id,
            "status": exp.status,
            "url": url,
            "filename": filename,
            "expires_at": 300,
        }
